# Auto-generated by compose2nix.
{
  pkgs,
  lib,
  config,
  ...
}: {
  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."omada-controller" = {
    image = "mbentley/omada-controller:6.1";
    environment = {
      "TZ" = "America/New_York";
      "WEB_CONFIG_OVERRIDE" = "false";
    };
    volumes = [
      "omada_omada-data:/opt/tplink/EAPController/data:rw"
      "omada_omada-logs:/opt/tplink/EAPController/logs:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=host"
    ];
  };
  systemd.services."podman-omada-controller" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-volume-omada_omada-data.service"
      "podman-volume-omada_omada-logs.service"
    ];
    requires = [
      "podman-volume-omada_omada-data.service"
      "podman-volume-omada_omada-logs.service"
    ];
    partOf = [
      "podman-compose-omada-root.target"
    ];
    wantedBy = [
      "podman-compose-omada-root.target"
    ];
  };

  # Volumes
  systemd.services."podman-volume-omada_omada-data" = {
    path = [pkgs.podman];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect omada_omada-data || podman volume create omada_omada-data
    '';
    partOf = ["podman-compose-omada-root.target"];
    wantedBy = ["podman-compose-omada-root.target"];
  };
  systemd.services."podman-volume-omada_omada-logs" = {
    path = [pkgs.podman];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect omada_omada-logs || podman volume create omada_omada-logs
    '';
    partOf = ["podman-compose-omada-root.target"];
    wantedBy = ["podman-compose-omada-root.target"];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-omada-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
